#lang racket
(require "core.rkt")
(define minium-fraction 16)
(define current-timbre (lambda (pitch duration) (synth-note "vgame" 49 pitch duration)))
(define minium-duration (round (/ (default-sample-rate) 8)))

(define (set-current-timbre timbre)
  (set! current-timbre timbre))
(define (set-current-tempo fraction tempo)
  (set! minium-duration (round (/ tempo (/ minium-fraction fraction)))))
(define (set-minium-fraction fraction)
  (set! minium-duration (round (* minium-duration (/ minium-fraction fraction))))
  (set! minium-fraction fraction))
(provide set-current-timbre)
(provide set-current-tempo)
(provide set-minium-fraction)
(provide minium-fraction)
(provide current-timbre)
(provide minium-duration)
