#lang racket
(define (set-root segment new-root)
  (send segment set-root new-root))
(define (rise-root segment change-of-pitch)
  (send segment rise-root change-of-pitch))
(define (set-duration segment new-duration)
  (send segment set-duration new-duration))
(define (set-volumn segment new-volumn)
  (send segment set-volumn new-volumn))
(define (get-volumn segment)
  (get-field volumn segment))
(define (set-timbre segment new-timbre)
  (send segment set-timbre new-timbre))
(define (scale-volumn segment scale)
  (send segment scale-volumn scale))
(provide set-duration)
(provide set-root)
(provide rise-root)
(provide set-volumn)
(provide get-volumn)
(provide scale-volumn)
(provide set-timbre)
